package com.crimeportal.crime_portal_backend.service;

import com.crimeportal.crime_portal_backend.exception.ResourceNotFoundException;
import com.crimeportal.crime_portal_backend.model.User;
import com.crimeportal.crime_portal_backend.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class UserService {
    private final UserRepository repo;
    public UserService(UserRepository repo) {
        this.repo = repo;
    }

    public List<User> getAllUsers() {
        return repo.findAll();
    }

    public User getUser(Long id) {
        return repo.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id " + id));
    }

    public User createUser(User user) {
        if (user.getRole() == null || user.getRole().isBlank()) {
            user.setRole("CITIZEN"); // business default[1]
        }
        return repo.save(user); // id generated by DB via IDENTITY[1]
    }

    public User updateUser(Long id, User updated) {
        User existing = getUser(id);
        existing.setName(updated.getName());
        existing.setEmail(updated.getEmail());
        existing.setPassword(updated.getPassword());
        existing.setPhone(updated.getPhone());
        // optional: prevent role changes here, or keep default if not provided
        if (updated.getRole() != null && !updated.getRole().isBlank()) {
            existing.setRole(updated.getRole());
        }
        return repo.save(existing);
    }

    public void deleteUser(Long id) {
        User existing = getUser(id);
        repo.delete(existing);
    }

    // Simple login for now (plain password); upgrade to BCrypt + tokens later
    public User login(String email, String password) {
        return repo.findByEmail(email)
                .filter(u -> u.getPassword().equals(password)) // replace with BCrypt check later
                .orElseThrow(() -> new ResourceNotFoundException("Invalid credentials"));
    }
}